#!/bin/bash

echo
echo 'Ti avvicini alla statua.'
echo
echo 'Sembra raffigurare una figura mostruosa (un "demone").'
echo
echo 'Tocchi la statua per analizzarla...'
echo '(premi INVIO per continuare)'
echo

read

echo 'La statua prende vita e cerca di colpirti!'
echo
echo 'Per scappare dalla stanza, digita:	cd ..'
echo 'Per scappare più velocemente, digita:	cd ../../..'
echo
echo "Ritorna all'inizio della stanza1."
echo



































































# La stanza sembra contenere una statua, ma non riesci a vederla bene.
#
# Questo non è un normale file di testo, ma è un programma eseguibile,
# perchè "ls -l" mostra la "x" di "eXecutable".
#
# Per eseguire un programma, devi digitarne il percorso.
#
# In questo caso, puoi digitare: ./statua
# Il punto "." indica alla shell che il programma è nella directory corrente.

